"""
Pydantic request and response models for the KiranaIQ assessment API.

These schemas are the single contract between the FastAPI backend and the
Streamlit frontend. Both engineers code against these models exclusively.
No field may be added to the API response without first adding it here.

All monetary values are in Indian Rupees (₹) as integers.
All scores are floats in the range [0.0, 1.0] unless otherwise noted.
All ranges are two-element lists [lower_bound, upper_bound].
"""

from __future__ import annotations

import time
from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


# ---------------------------------------------------------------------------
# Request model
# ---------------------------------------------------------------------------

class AssessmentRequest(BaseModel):
    """
    Payload sent by the Streamlit frontend (or field agent SDK) to initiate
    a KiranaIQ cash flow assessment.

    Images are sent as multipart/form-data files alongside this form data.
    """

    gps_lat: float = Field(
        ...,
        ge=6.0,
        le=37.5,
        description="Decimal degrees latitude. Must be within India bounds.",
        examples=[21.1458],
    )
    gps_lon: float = Field(
        ...,
        ge=68.0,
        le=97.5,
        description="Decimal degrees longitude. Must be within India bounds.",
        examples=[79.0882],
    )
    capture_timestamp: int = Field(
        default_factory=lambda: int(time.time()),
        description="Unix epoch timestamp of image capture. Used for HMAC binding.",
    )
    hmac_commitments: List[str] = Field(
        default_factory=list,
        min_length=0,
        max_length=5,
        description=(
            "Per-image HMAC-SHA256 commitments generated by the Android SDK "
            "at capture time. Empty list is accepted in demo mode."
        ),
    )
    shop_size_sqft: Optional[int] = Field(
        None,
        ge=10,
        le=5000,
        description="Self-reported shop floor area in square feet.",
    )
    monthly_rent_inr: Optional[int] = Field(
        None,
        ge=0,
        le=500_000,
        description=(
            "Monthly rent in INR. Set to 0 only when property_owned=True. "
            "If property_owned=False and this is 0 or None, the geo-prior "
            "for the area is used as a fallback."
        ),
    )
    property_owned: bool = Field(
        default=False,
        description=(
            "True if the merchant owns the commercial property. "
            "Bypasses rent geo-prior fraud checks and applies the "
            "property ownership confidence premium (1.08×)."
        ),
    )
    years_in_operation: Optional[int] = Field(
        None,
        ge=0,
        le=60,
        description=(
            "Self-reported years the store has been operating. "
            "Used to compute the Lindy Effect vintage confidence multiplier."
        ),
    )
    sdk_attested: bool = Field(
        default=False,
        description=(
            "True if the Android SDK passed Play Integrity attestation. "
            "In demo mode this is always accepted as-is."
        ),
    )

    @field_validator("capture_timestamp")
    @classmethod
    def timestamp_not_in_future(cls, v: int) -> int:
        """Reject timestamps more than 5 minutes in the future (clock skew tolerance)."""
        now = int(time.time())
        if v > now + 300:
            raise ValueError(
                f"capture_timestamp {v} is in the future. "
                "Possible GPS binding attack or device clock error."
            )
        return v

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "gps_lat": 21.1458,
                "gps_lon": 79.0882,
                "capture_timestamp": 1714500000,
                "hmac_commitments": [],
                "shop_size_sqft": 80,
                "monthly_rent_inr": 8000,
                "property_owned": False,
                "years_in_operation": 14,
                "sdk_attested": False,
            }
        }
    )


# ---------------------------------------------------------------------------
# Nested response sub-models
# ---------------------------------------------------------------------------

class IncomeCalculation(BaseModel):
    """
    Transparent breakdown of the gross → net income derivation.
    Every line item must be present so the RBI audit trail is complete.
    """

    gross_monthly_range: List[int] = Field(
        ...,
        description="Gross income estimate before OPEX deductions. [lower, upper] ₹.",
    )
    rent_deducted: int = Field(
        ...,
        description="Effective monthly rent deducted (₹). Zero if property_owned=True.",
    )
    rent_source: str = Field(
        ...,
        description=(
            "Origin of the rent figure: "
            "'declared' | 'geo_prior' | 'zero_owned'."
        ),
    )
    property_owned: bool = Field(
        ...,
        description="Whether the merchant owns their commercial property.",
    )
    ownership_premium: float = Field(
        ...,
        description=(
            "Confidence multiplier applied for property ownership. "
            "1.08 if owned, 1.00 if renting."
        ),
    )
    rent_flags: List[str] = Field(
        default_factory=list,
        description="Any rent-specific fraud or risk flags raised.",
    )


class SeasonalityProfile(BaseModel):
    """
    12-month income simulation derived from category mix × seasonal indices.
    Used to compute the step-EMI schedule and trough-based EMI ceiling.
    """

    monthly_estimates: List[int] = Field(
        ...,
        description="Estimated net income for each of the 12 calendar months (₹).",
        min_length=12,
        max_length=12,
    )
    trough_month: str = Field(
        ...,
        description="Name of the lowest-income month (e.g., 'July').",
    )
    trough_income: int = Field(
        ...,
        description="Estimated income in the trough month (₹).",
    )
    peak_month: str = Field(
        ...,
        description="Name of the highest-income month (e.g., 'November').",
    )
    peak_income: int = Field(
        ...,
        description="Estimated income in the peak month (₹).",
    )
    seasonality_risk_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "Coefficient of variation of monthly income. "
            "0 = perfectly stable, 1 = highly seasonal."
        ),
    )
    recommended_emi_ceiling: int = Field(
        ...,
        description=(
            "Maximum safe EMI (₹), computed as trough_income × 40% FOIR. "
            "This is the most conservative, RBI-defensible EMI figure."
        ),
    )
    step_emi_schedule: str = Field(
        ...,
        description=(
            "Human-readable step-EMI recommendation "
            "(e.g., '₹6,000/mo Jul–Aug · ₹10,000/mo rest of year')."
        ),
    )


class TemporalFraudScores(BaseModel):
    """
    Results from the on-device (or server-side in production) temporal
    fraud analysis of the optional 10-second video submission.
    Sentinel value -1.0 means the check was bypassed (e.g., luminance gate).
    """

    t1_staging_score: float = Field(
        ...,
        ge=-1.0,
        le=1.0,
        description=(
            "Inventory staging score. Histogram similarity between first and "
            "last video frame. > 0.5 suggests borrowed/staged goods. "
            "-1.0 = not computed."
        ),
    )
    t2_static_bg_score: float = Field(
        ...,
        ge=-1.0,
        le=1.0,
        description=(
            "Static background score. Optical flow foreground/background "
            "differential. > 0.5 suggests deepfake backdrop. -1.0 = bypassed."
        ),
    )
    t3_occlusion_score: float = Field(
        ...,
        ge=-1.0,
        le=1.0,
        description=(
            "Hand occlusion score. Skin-tone pixel ratio in shelf region. "
            "> 0.5 suggests hand-held inventory. -1.0 = bypassed."
        ),
    )
    luminance_mean: float = Field(
        default=-1.0,
        description=(
            "Mean frame luminance (0–255 scale). "
            "< 35 = luminance gate active, T-2/T-3 bypassed."
        ),
    )
    pipeline_bypassed: bool = Field(
        default=False,
        description="True if luminance was too low to run optical flow reliably.",
    )
    flags: List[str] = Field(
        default_factory=list,
        description="Temporal fraud flags raised (e.g., 'temporal_inventory_staging_suspected').",
    )
    video_submitted: bool = Field(
        default=False,
        description="False if no video was uploaded; temporal checks were not attempted.",
    )


class PeerBenchmark(BaseModel):
    """
    Comparison of this store against verified peer stores with similar
    geographic and operational profiles.
    """

    peer_count: int = Field(
        ...,
        description="Number of verified peer stores used in this benchmarking.",
    )
    income_percentile: int = Field(
        ...,
        ge=0,
        le=100,
        description="This store's estimated income percentile among peers (0–100).",
    )
    peer_median_daily_sales: int = Field(
        ...,
        description="Median daily sales of peer stores (₹).",
    )
    peer_p25_daily_sales: int = Field(
        ...,
        description="25th percentile daily sales of peer stores (₹).",
    )
    peer_p75_daily_sales: int = Field(
        ...,
        description="75th percentile daily sales of peer stores (₹).",
    )
    footfall_opportunity_score: float = Field(
        ...,
        description=(
            "Estimated under-earning relative to location potential. "
            "Positive = store earns less than location supports (growth capacity). "
            "Negative = store over-earns (may be unsustainable)."
        ),
    )
    benchmark_confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Reliability of this benchmark. Low if peer_count < 10.",
    )


class ConfidenceBreakdown(BaseModel):
    """
    Transparent decomposition of the composite confidence score.
    Required for RBI Digital Lending Guidelines explainability compliance.
    """

    image_quality: float = Field(..., ge=0.0, le=1.0)
    signal_consistency: float = Field(..., ge=0.0, le=1.0)
    geo_completeness: float = Field(..., ge=0.0, le=1.0)
    fraud_clear: float = Field(..., ge=0.0, le=1.0)
    model_certainty: float = Field(..., ge=0.0, le=1.0)
    vintage_multiplier: float = Field(..., ge=0.0, le=1.1)
    fraud_penalty: float = Field(..., ge=0.0, le=1.0)
    ownership_premium: float = Field(..., ge=0.0, le=1.1)
    vintage_label: str = Field(
        ...,
        description="Human-readable vintage category (e.g., 'established', 'legacy_lindy').",
    )


class CascadeTierInfo(BaseModel):
    """
    Which processing tier was used and its associated cost.
    Displayed in the Streamlit UI as a badge.
    """

    tier: int = Field(..., description="0, 1, 2, or 3.")
    tier_label: str = Field(
        ...,
        description="Human-readable tier name (e.g., 'Tier 2 — Structured').",
    )
    estimated_cost_inr: int = Field(
        ...,
        description="Approximate API cost for this assessment (₹).",
    )
    providers_used: List[str] = Field(
        ...,
        description="Names of providers invoked (e.g., ['MockVision', 'MockGeo']).",
    )


# ---------------------------------------------------------------------------
# Primary response model
# ---------------------------------------------------------------------------

class AssessmentResponse(BaseModel):
    """
    Complete KiranaIQ assessment result.

    This is the canonical output format promised in the Round 1 pitch deck.
    Every field shown in the slide 4 JSON specimen is present here.
    The Streamlit dashboard reads exclusively from this model.
    """

    # Identity
    assessment_id: str = Field(
        ...,
        description="Unique assessment identifier (e.g., 'KIQ-A1B2C3D4E5F6').",
    )
    processing_time_ms: int = Field(
        ...,
        description="Total server-side processing time in milliseconds.",
    )
    mode: str = Field(
        ...,
        description="Runtime mode at time of assessment: 'demo' or 'production'.",
    )

    # Core cash flow estimates
    daily_sales_range: List[int] = Field(
        ...,
        min_length=2,
        max_length=2,
        description="Estimated daily sales range [lower, upper] in ₹.",
    )
    monthly_revenue_range: List[int] = Field(
        ...,
        min_length=2,
        max_length=2,
        description="Estimated gross monthly revenue range [lower, upper] in ₹.",
    )
    monthly_income_range: List[int] = Field(
        ...,
        min_length=2,
        max_length=2,
        description="Estimated net monthly income range [lower, upper] in ₹ after rent.",
    )
    interval_coverage: float = Field(
        default=0.80,
        description=(
            "Statistical coverage guarantee of the reported intervals. "
            "0.80 = these ranges will contain the true value 80% of the time."
        ),
    )

    # Economic sub-models
    income_calculation: IncomeCalculation
    seasonality: SeasonalityProfile
    peer_benchmark: PeerBenchmark

    # Credit output
    recommended_credit_limit: List[int] = Field(
        ...,
        min_length=2,
        max_length=2,
        description="Recommended credit limit range [lower, upper] in ₹.",
    )
    emi_affordability_score: int = Field(
        ...,
        ge=0,
        le=100,
        description=(
            "EMI affordability score (0–100). "
            "75+ = strong, 50–74 = moderate, <50 = caution."
        ),
    )

    # Store signals
    store_type: str = Field(
        ...,
        description=(
            "Classified store archetype: "
            "'kirana_primary' | 'kirana_pharma_hybrid' | "
            "'kirana_mobile_hybrid' | 'general_store'."
        ),
    )
    category_mix: Dict[str, float] = Field(
        ...,
        description="Category weight vector (e.g., {'staples': 0.42, 'fmcg': 0.31}).",
    )
    fmvc_ratio: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "Fast-Moving vs. Slow-Moving inventory ratio. "
            "Higher = better cash conversion velocity."
        ),
    )

    # Confidence
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Composite confidence score (0–1).",
    )
    confidence_tier: str = Field(
        ...,
        description=(
            "Named confidence tier: "
            "'high' (≥0.80) | 'medium' (≥0.60) | "
            "'low' (≥0.40) | 'insufficient' (<0.40)."
        ),
    )
    confidence_tier_interpretation: str = Field(
        ...,
        description="One-sentence human-readable explanation of the confidence tier.",
    )
    confidence_breakdown: ConfidenceBreakdown

    # Fraud
    fraud_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Composite fraud score (0 = clean, 1 = certain fraud).",
    )
    fraud_flags: List[str] = Field(
        default_factory=list,
        description="Fraud-specific flags raised (e.g., 'hmac_binding_failure').",
    )
    risk_flags: List[str] = Field(
        default_factory=list,
        description="Non-fraud risk flags (e.g., 'low_light_enhanced', 'rent_not_declared').",
    )
    temporal: TemporalFraudScores

    # Processing metadata
    cascade_tier: CascadeTierInfo

    # Decision
    recommendation: str = Field(
        ...,
        description=(
            "Underwriting recommendation: "
            "'approve' | 'approve_with_monitoring' | "
            "'needs_field_verification' | "
            "'reject_fraud_suspected' | 'reject_insufficient_income'."
        ),
    )
    underwriter_narrative: str = Field(
        ...,
        description=(
            "Plain-English credit summary for the underwriter. "
            "References key signal drivers and the recommendation rationale."
        ),
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "assessment_id": "KIQ-A1B2C3D4E5F6",
                "processing_time_ms": 312,
                "mode": "demo",
                "daily_sales_range": [6200, 8800],
                "monthly_revenue_range": [186000, 264000],
                "monthly_income_range": [28000, 44000],
                "interval_coverage": 0.80,
                "confidence_score": 0.74,
                "confidence_tier": "medium",
                "confidence_tier_interpretation": (
                    "Sufficient for conditional approval. "
                    "One or more signals require field confirmation."
                ),
                "fraud_score": 0.11,
                "fraud_flags": [],
                "risk_flags": ["rent_not_declared_using_area_prior"],
                "recommendation": "approve_with_monitoring",
                "underwriter_narrative": (
                    "Store shows consistent FMCG mix. SDI 0.74. "
                    "Arterial road + bus depot 38m. Peer 67th percentile. "
                    "Approve at lower bound. 3-month review recommended."
                ),
            }
        }
    )


# ---------------------------------------------------------------------------
# Health check response model
# ---------------------------------------------------------------------------

class HealthResponse(BaseModel):
    """Response model for the /health endpoint."""

    status: str = Field(default="ok")
    version: str
    mode: str
    message: str
